name: Image Push
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: lcs-load-generator
          context: .
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      - name: Push Image to Quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: quay.io/rh-ee-bbodapat
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
